/**
 * Setup script to create .env.local file
 * 
 * Run this with: node setup-env.js YOUR_API_KEY
 */

const fs = require('fs');
const path = require('path');

// Get API key from command line argument
const apiKey = process.argv[2];

if (!apiKey) {
  console.error('\x1b[31m%s\x1b[0m', 'Error: No API key provided!');
  console.log('\x1b[33m%s\x1b[0m', 'Usage: node setup-env.js YOUR_API_KEY');
  console.log('\x1b[36m%s\x1b[0m', 'Example: node setup-env.js sk-1234567890abcdef');
  process.exit(1);
}

// Create or update .env.local file
const envContent = `# OpenAI API key for accessing language models
# Generated by setup-env.js script
OPENAI_API_KEY=${apiKey}
`;

const envPath = path.join(__dirname, '.env.local');

try {
  fs.writeFileSync(envPath, envContent);
  console.log('\x1b[32m%s\x1b[0m', '✅ .env.local file created successfully!');
  console.log('\x1b[36m%s\x1b[0m', `API key has been saved to: ${envPath}`);
  console.log('\x1b[33m%s\x1b[0m', 'Remember to restart your development server for changes to take effect.');
} catch (error) {
  console.error('\x1b[31m%s\x1b[0m', `Error creating .env.local file: ${error.message}`);
  process.exit(1);
} 